package com.swingtrade.domain;

import java.time.LocalDate;

/**
 * Represents a trading signal generated by a strategy or analysis tool.
 * This record captures the decision-making information for a specific stock on a specific date.
 *
 * @param symbol     the stock symbol (e.g., "AAPL")
 * @param date       the date when the signal was generated
 * @param type       the signal type (BUY, SELL, or HOLD)
 * @param confidence the confidence level of the signal (0.0 to 1.0)
 * @param reasoning  the textual explanation for the signal
 */
public record Signal(
    String symbol,
    LocalDate date,
    SignalType type,
    Double confidence,
    String reasoning
) {
    /**
     * Enum representing the different types of trading signals.
     */
    public enum SignalType {
        BUY,
        SELL,
        HOLD
    }
}
