# Server configuration
server.port=8080

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Micrometer configuration
management.metrics.enable.all=true
management.metrics.web.server.request.autotime.enabled=true

# Logging
logging.level.com.swingtrade.api=DEBUG
