package com.swingtrade.domain;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Represents a trading signal generated by the strategy engine.
 * Signals indicate recommended actions (BUY, SELL, HOLD) for a specific stock
 * on a specific date, along with confidence levels and reasoning.
 *
 * @param id         the unique identifier for the signal (database auto-generated)
 * @param symbol     the stock symbol (e.g., "RELIANCE", "TCS")
 * @param date       the date when the signal was generated
 * @param type       the signal type (BUY, SELL, or HOLD)
 * @param confidence the confidence level of the signal (0.0 to 1.0)
 * @param reasoning  the textual explanation for the signal
 * @param entryPrice the recommended entry price zone (high)
 * @param stopLoss   the stop loss price level
 * @param target     the target price for profit taking
 * @param riskReward the calculated risk-reward ratio
 * @param indicators the technical indicators that triggered the signal
 * @param generatedAt the timestamp when the signal was generated
 * @param strategy the strategy variant id that produced the signal (null when not recorded)
 * @param strategyVersion the strategy configuration version (null when not recorded)
 */
public record Signal(
    Long id,
    String symbol,
    LocalDate date,
    SignalType type,
    BigDecimal confidence,
    String reasoning,
    BigDecimal entryPrice,
    BigDecimal stopLoss,
    BigDecimal target,
    BigDecimal riskReward,
    String indicators,
    LocalDate generatedAt,
    String sentimentScore,
    String sentimentReasoning,
    String strategy,
    Integer strategyVersion
) {
    /** Form for callers that carry no strategy provenance (strategy and version are null). */
    public Signal(Long id, String symbol, LocalDate date, SignalType type, BigDecimal confidence,
                  String reasoning, BigDecimal entryPrice, BigDecimal stopLoss, BigDecimal target,
                  BigDecimal riskReward, String indicators, LocalDate generatedAt, String sentimentScore,
                  String sentimentReasoning) {
        this(id, symbol, date, type, confidence, reasoning, entryPrice, stopLoss, target, riskReward,
            indicators, generatedAt, sentimentScore, sentimentReasoning, null, null);
    }

    /**
     * Enum representing the different types of trading signals.
     */
    public enum SignalType {
        BUY("Buy Signal"),
        SELL("Sell Signal"),
        HOLD("Hold");

        private final String description;

        SignalType(String description) {
            this.description = description;
        }

        public String getDescription() {
            return description;
        }
    }

    /**
     * Validates and creates a signal with normalized confidence.
     *
     * @param symbol the stock symbol
     * @param date the signal date
     * @param type the signal type
     * @param confidence the confidence (will be clamped to 0-1)
     * @param reasoning the signal reasoning
     * @return a new Signal instance
     */
    public static Signal create(
        String symbol,
        LocalDate date,
        SignalType type,
        BigDecimal confidence,
        String reasoning
    ) {
        BigDecimal normalizedConfidence = confidence
            .max(BigDecimal.ZERO)
            .min(BigDecimal.ONE);
        return new Signal(
            null,
            symbol,
            date,
            type,
            normalizedConfidence,
            reasoning,
            null,
            null,
            null,
            null,
            null,
            LocalDate.now(),
            null,
            null
        );
    }

    /**
     * Returns true if this is a BUY signal.
     *
     * @return true if BUY
     */
    public boolean isBuySignal() {
        return SignalType.BUY == type;
    }

    /**
     * Returns true if this is a SELL signal.
     *
     * @return true if SELL
     */
    public boolean isSellSignal() {
        return SignalType.SELL == type;
    }

    /**
     * Returns true if this is a HOLD signal.
     *
     * @return true if HOLD
     */
    public boolean isHoldSignal() {
        return SignalType.HOLD == type;
    }
}
